### ISSUE TITLE
My prefer effect is bugged

### ISSUE THREAD

**Issue by psychomuser** [BazaJayGee66/homeassistant_cololight#13]
Hi, sorry for my english language.
I love your integration, and I love the shadow effect of cololight.

My prefer effect is:
Color Scheme: Shadow | Red, Yellow
Cycle Speed: 24
Mode: 13

If I create this effect from integration menu, the cololight lamp shows a effect with Red, Yellow AND GREEN. Why does it turn green?
With the official Lifesmart App this effect work properly.
I tried with different cycle speeds and mode, but the issue still remain.

I tried with different color ("red, white", "Yellow, White" ecc), and this effect work properly (without adding wrong colors).

PS: i can't create the effect manually, I tried to add to the configuration.yaml this strings:

```
light:
  - platform: cololight
    name: Cololight
    host: 192.168.188.25
    custom_effects:
      - name: RedYellow
        color_scheme: Shadow
        color: Red, Yellow
        cycle_speed: 24
        mode: 13
```

but it doesn't work, even after reboot.

Thank You for your helps, and for creating this integration :)
